community/serie: fix build on ppc64le and s390x
Update rustix crate to 1.1.5 to fix build error with rust >=1.98 on
ppc64le and s390x.

```
error[E0659]: `STATX_TYPE` is ambiguous
   --> /builds/qaqland/aports/community/serie/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.4/src/fs/statx.rs:75:25
    |
 75 |         const TYPE = c::STATX_TYPE;
    |                         ^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `STATX_TYPE` could refer to the constant imported here
   --> /builds/qaqland/aports/community/serie/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.4/src/backend/libc/c.rs:7:16
    |
  7 | pub(crate) use libc::*;
    |                ^^^^^^^
    = help: consider adding an explicit import of `STATX_TYPE` to disambiguate
note: `STATX_TYPE` could also refer to the constant imported here
   --> /builds/qaqland/aports/community/serie/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.4/src/backend/libc/c.rs:512:16
    |
512 | pub(crate) use statx_flags::*;
    |                ^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `STATX_TYPE` to disambiguate
```

Also use `$CHOST` instead of `$CTARGET` triple in `cargo fetch` per
abuild@56297c0c.