community/gleam: upgrade to 1.19.1
1. https://github.com/gleam-lang/gleam/releases/tag/v1.19.1
2. Upstream renamed echo.rs to output.rs in test-output/src/tests/, which caused
skip-bun-case.patch and skip-deno-case.patch to fail to apply.
- Update the patches to match the new file name
- Merge the two patches into skip-bun-and-deno-case.patch
3. fix build with rust >=1.98 on ppc64le (update rustix crate to 1.1.5)
```
error[E0659]: `STATX_INO` is ambiguous
   --> /builds/huajingyun01/aports/community/gleam/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.4/src/fs/statx.rs:99:24
    |
 99 |         const INO = c::STATX_INO;
    |                        ^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `STATX_INO` could refer to the constant imported here
   --> /builds/huajingyun01/aports/community/gleam/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.4/src/backend/libc/c.rs:7:16
    |
  7 | pub(crate) use libc::*;
    |                ^^^^^^^
    = help: consider adding an explicit import of `STATX_INO` to disambiguate
note: `STATX_INO` could also refer to the constant imported here
   --> /builds/huajingyun01/aports/community/gleam/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.4/src/backend/libc/c.rs:512:16
    |
512 | pub(crate) use statx_flags::*;
    |                ^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `STATX_INO` to disambiguate
```