community/youtube-tui: upgrade to 0.9.4, enable on loongarch64
https://github.com/Siriusmart/youtube-tui/compare/v0.9.3...v0.9.4/

Refresh the bindgen patch for the new version.

Update rustix crate to 1.1.5 to fix build error with rust >=1.98 on
ppc64le and s390x. Re-enable on loongarch64.

```
error[E0659]: `STATX_TYPE` is ambiguous
    --> [...]/aports/community/youtube-tui/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.2/src/fs/statx.rs:75:25
     |
  75 |         const TYPE = c::STATX_TYPE;
     |                         ^^^^^^^^^^ ambiguous name
     |
     = note: ambiguous because of multiple glob imports of a name in the same module
 note: `STATX_TYPE` could refer to the constant imported here
    --> [...]/aports/community/youtube-tui/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.2/src/backend/libc/c.rs:7:16
     |
   7 | pub(crate) use libc::*;
     |                ^^^^^^^
     = help: consider adding an explicit import of `STATX_TYPE` to disambiguate
 note: `STATX_TYPE` could also refer to the constant imported here
    --> [...]/aports/community/youtube-tui/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.1.2/src/backend/libc/c.rs:524:16
     |
 524 | pub(crate) use statx_flags::*;
     |                ^^^^^^^^^^^^^^
     = help: consider adding an explicit import of `STATX_TYPE` to disambiguate
```