main/py3-ptyprocess: fix build with flit >=4.0.0
Update `pyproject.toml` metadata fields for compatibility with flit >=4.0.0.

```
Traceback (most recent call last):
  File "/usr/bin/gpep517", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.14/site-packages/gpep517/__main__.py", line 238, in main
    return func(args)
  File "/usr/lib/python3.14/site-packages/gpep517/__main__.py", line 45, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/gpep517/build.py", line 180, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
  File "/usr/lib/python3.14/site-packages/flit_core/buildapi.py", line 74, in build_wheel
    info = make_wheel_in(pyproj_toml, Path(wheel_directory))
  File "/usr/lib/python3.14/site-packages/flit_core/wheel.py", line 222, in make_wheel_in
    wb = WheelBuilder.from_ini_path(ini_path, fp)
  File "/usr/lib/python3.14/site-packages/flit_core/wheel.py", line 86, in from_ini_path
    ini_info = read_flit_config(ini_path)
  File "/usr/lib/python3.14/site-packages/flit_core/config.py", line 75, in read_flit_config
    return prep_toml_config(d, path)
  File "/usr/lib/python3.14/site-packages/flit_core/config.py", line 91, in prep_toml_config
    raise ConfigError(
    ...<3 lines>...
    )
flit_core.config.ConfigError: The [tool.flit.metadata] table is no longer supported. Switch to the standard [project] table or require flit_core<4 to build this package.
```